[package]
name = "chameleon"
version = "0.0.1"
authors = ["Nate Yazdani <nyazdani@cs.washington.edu>", "Matt Brubeck <mbrubeck@limpet.net>"]

[[bin]]
name = "chameleon"
path = "src/main.rs"

[dependencies]
getopts = "0.2.19"
image = "0.14"
